# config.yaml - Put this file in the same directory as main.py
random_seed: 42

model:
  type: BayesianMLP # options: BayesianMLP, InputWeigtedBNN, TemperedBNN
  hidden_size: 20

training:
  batch_size: 64
  lr: 0.001
  epochs: 1000

dataset:
  name: ToyDataset
  num_samples: 512
  train_split: 0.8
